### ISSUE TITLE
GUI makes the Time Engine broke, or something like that

### ISSUE THREAD

**Issue by azimme2s** [HBRS-MAAS/project-awesomebakery#49]
Every Time the GUI is active, no Orders will pass trough the Bakeries.
I get exceptions like this:

org.awesomebakery.PastDateException: The requested wake up is at <1.1.0.0> but the current date is <512.0.0.0>
        at org.awesomebakery.TimeEngine.registerWakeUp(TimeEngine.java:58)
        at org.awesomebakery.agents.CustomerAgent.lambda$setup$bd19a2c8$1(CustomerAgent.java:30)
        at org.awesomebakery.behaviors.FindAgentBehaviour.action(FindAgentBehaviour.java:48)
        at jade.core.behaviours.Behaviour.actionWrapper(Behaviour.java:344)
        at jade.core.Agent$ActiveLifeCycle.execute(Agent.java:1585)
        at jade.core.Agent.run(Agent.java:1524)
        at java.lang.Thread.run(Thread.java:748)

so the wake up call is probably to late, but when I deactived the GUI it works fine.
Any Ideas why?

**Comment by mwiktorin** [comment]
this looks like the time engine is finished before the orders are placed.
I pulled the streetnetwork branch and launched it with the gui and it was working for me.

**Comment by azimme2s** [comment]
Maybe it could be my Laptop?
Because it is not a developer Laptop :/

**Comment by moriarty** [comment]
> Maybe it could be my Laptop?
Because it is not a developer Laptop :/

I think that's unlikely... Unless your laptop is a few decades old, these projects don't require intensive computation.

**Comment by azimme2s** [comment]
Okay funny, because I set a thread for 2000 milliseconds to sleep, instead of 1000, and on the Laptop it works fine, on my desk computer at Home it works fine with 1000 milliseconds.
